### ISSUE TITLE
Update Resources to use generated Res classes

### ISSUE THREAD

**Issue by Kashif-E** [Kashif-E/KMPMovies#13]
Compose resources generate Res classes which give type safe access to resources.
Resources like drawables, strings, and fonts should be used by generated accessors. Not by path.

**Comment by mahramane** [comment]
Hi
How can i generate the Res.kt class?
i download the KMPMovies project but i give the following error: 
`Unresolved reference: Res`

**Comment by Kashif-E** [comment]
@mahramane  rebuild your project
